# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='card',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
