name: 'Build'
on: 
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
            npm install

      - name: lint
        run: |
            npm run lint

  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
            npm install

      - name: dist-win64
        run: |
            npm run dist:win64
        
      - name: dist-linux
        run: |
            npm run dist:linux64
