name: 'Build'
on: 
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
