name: 'Build & Dist'
on: 
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
            npm install

      - name: lint
        run: |
            npm run lint

  dist-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - run: |
            npm install

      - name: dist-linux
        run: |
            npm run dist:linux

      - uses: actions/upload-artifact@v2
        with:
          name: out-linux
          path: out/make

  dist-win:
    runs-on: windows-latest
    needs: build
    steps: 
       - uses: actions/checkout@v2
       
       - run: |
           npm install

       - name: dist-win
         run: |
           npm run dist:win

       - uses: actions/upload-artifact@v2
         with:
           name: out-win
           path: out/make

            

